name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - stage
        - prod

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: ['dev', 'stage', 'prod']

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Newman
      run: |
        npm install -g newman
        npm install -g newman-reporter-htmlextra

    - name: Run Newman Tests
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          env="${{ github.event.inputs.environment }}"
        else
          env="${{ matrix.environment }}"
        fi
        newman run "Simple Price Test.postman_collection.json" \
        -e "${env}.postman_environment.json" \
        -r cli,htmlextra \
        --reporter-htmlextra-export "newman-report-${env}.html"

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: newman-test-results-${{ matrix.environment }}
        path: newman-report-*.html
