name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Use the version of Node.js you prefer

    - name: Install Newman
      run: |
        npm install -g newman
        npm install -g newman-reporter-htmlextra # Optional: for HTML report

    - name: Run Newman Tests
      run: |
        newman run "Simple Price Test.postman_collection.json" -e "dev.postman_environment.json"
