name: K6 Performance Tests

on:
  workflow_dispatch:  # This allows manual execution

jobs:
  performance-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Snapd
        run: |
          sudo apt update
          sudo apt install -y snapd

      - name: Install K6 using Snap
        run: |
          sudo snap install k6

      - name: Run K6 Performance Test
        run: k6 run performanceTest.js --out json=performanceTest.json

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Generate HTML Report
        run: |
          npm install -g html-reporter
          html-reporter -i performanceTest.json -o performanceTest.html

      - name: Upload HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: k6-performance-test-report
          path: performanceTest.html
